### ISSUE TITLE
launchpad is still being used as a bug tracker?

### ISSUE THREAD

**Issue by gforcada** [plone/plone.recipe.alltests#3]
I noticed that at the end of the README.rst there's a reference to a [Launchpad](https://bugs.launchpad.net/collective.buildout) bug tracker, is that still used?

Should it be closed and move over here all bug reports?

There seems to be [13 patches there also](https://bugs.launchpad.net/collective.buildout/+patches)...

**Comment by tisto** [comment]
Nope. We should remove that link and point to the github issue tracker. I think none of the patches is for plone.recipe.alltests.

**Comment by gforcada** [comment]
Link fixed, closing :)
